export const NOTIFICATION_SEVERITIES = [
  'CRITICAL',
  'HIGH',
  'MEDIUM',
  'LOW',
  'WARNING',
  'INFO',
] as const;

export const NOTIFICATION_TYPES = [
  'COMMUNICATION_FAILURE',
  'CONTROLLER_OFFLINE',
  'CONTROLLER_ONLINE',
  'THRESHOLD_EXCEEDED',
  'HOOK_THRESHOLD_EXCEEDED',
  'HOOK_THRESHOLD',
  'BUCKLE_OPENED',
  'BUCKLE_OPEN',
  'DEVICE_OFFLINE',
  'DEVICE_ONLINE',
  'ALARM_TRIGGERED',
] as const;
