class NotificationSeverity:
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class NotificationType:
    CONTROLLER_OFFLINE = "CONTROLLER_OFFLINE"
    CONTROLLER_ONLINE = "CONTROLLER_ONLINE"
    BATTERY_LOW = "BATTERY_LOW"
    ALARM_TRIGGERED = "ALARM_TRIGGERED"
    THRESHOLD_EXCEEDED = "THRESHOLD_EXCEEDED"
    BUCKLE_OPENED = "BUCKLE_OPENED"
    COMMUNICATION_FAILURE = "COMMUNICATION_FAILURE"
